digisafe/account/urls.py
from django.urls import path, include

from .views import accountView, logoutView, loginView, loginLostView, \
    changePasswordView, resetPasswordView, setPosition, certificateView, \
    dissociateCompanyView, searchCourseView, calendarView, CalendarDelEventView, \
    CalendarFormEventView, CalendarAddView, coursesView, indexView, SettingsView, \
    WorkSessionView


urlpatterns = [
    path('', indexView, name="index"),
    path('courses/', coursesView, name="courses"),
    path('settings/<int:pk>/', SettingsView.as_view(), name="settings"),
    path('agenda/view/', calendarView, name="calendar"),
    path('agenda/set/<int:year>/<int:month>/', calendarView, name="calendar-set"),
    path('agenda/add/<int:year>/<int:month>/<int:day>/', CalendarAddView.as_view(), name="calendar-add"),
    path('agenda/edit/<int:pk>/date/<int:year>/<int:month>/<int:day>/',
         CalendarFormEventView.as_view(), name="calendar-edit"),
    path('agenda/del/<int:pk>/', CalendarDelEventView.as_view(), name="calendar-del"),

    path('company/<int:pk>/dissociate/', dissociateCompanyView, name="dissociate"),
    path('login/', loginView, name="login"),
    path('logout/', logoutView, name="logout"),
    path('loginlost/', loginLostView, name="login-lost"),
    path('changepassword/', changePasswordView, name="change-password"),
    path('resetpassword/', resetPasswordView, name="reset-password"),
    path('user/setposition', setPosition, name="setposition"),
    path('protocol/<int:pk_protocol>/view/', certificateView, name="view-certificate"),
    path('searchcourse/', searchCourseView, name="searchcourse"),

    # work session book
    path('worksessions/', WorkSessionView.as_view(), name="worksessions"),
]

digisafe/companies/urls.py
from django.urls import path, include

from .views import home, set_company
from .views import companyDetailView, companyPublicDetailView, requestAssociateToUser, requestAssociateToCompany
from .views import requestAssociateAction, retrieve_users_to_associate, requestDissociateAction
from .views import favoriteuser, list_users_from_map, retrive_users_from_map, book_user
from .views import SessionBookCreateView, SessionBookListView, SessionBookUpdateView, SessionBookDetailView,\
                    SessionBookDeleteView, openMap, send_invite_now, SettingsCompanyView, sessionBookUsers

urlpatterns = [
    path('home/', home, name="home"),
    path('<int:pk>/set/', set_company, name="set-company"),
    path('settings/', SettingsCompanyView.as_view(), name="setting"),

    path('<int:pk>/view/', companyDetailView, name="company-view"),
    path('<int:pk>/public/view/', companyPublicDetailView, name="company-public-view"),
    path('associateuser/', requestAssociateToUser, name="company-request-user"),
    path('<int:pk>/dissociateuseraction/', requestDissociateAction, name="company-dissociate-user"),
    path('associateuseraction/', requestAssociateAction, name="company-request-user-action"),
    path('associatecompany/', requestAssociateToCompany, name="user-request-company"),
    path('users/search/', retrieve_users_to_associate, name="company-user-search"),

    # map
    path('openmap/book/<int:session_id>/view/', openMap, name="openmap"),
    path('openmap/book/<int:session_id>/optionlist/', list_users_from_map, name="optionusers"),
    path('openmap/book/<int:session_id>/retriveoptionlist/', retrive_users_from_map, name="retriveoptionlist"),
    path('openmap/book/<int:session_id>/invite/', send_invite_now, name="send-invite"),

    path('favoriteuser/', favoriteuser, name="favoriteuser"),
    path('bookuser/', book_user, name="bookuser"),

    # work session
    path('sessionbook/list/', SessionBookListView.as_view(), name="sessionbook-list"),
    path('sessionbook/create/', SessionBookCreateView.as_view(), name="sessionbook-create"),
    path('sessionbook/<int:pk>/update/', SessionBookUpdateView.as_view(), name="sessionbook-update"),
    path('sessionbook/<int:pk>/delete/', SessionBookDeleteView.as_view(), name="sessionbook-delete"),
    # path('sessionbook/<int:pk>/detail/', SessionBookDetailView.as_view(), name="sessionbook-detail"),
    path('sessionbook/<int:pk>/bookresponse/', SessionBookDetailView.as_view(), name="sessionbook-bookresponse"),
    path('sessionbook/<int:pk>/users/', sessionBookUsers, name="sessionbook-users"),

]

digisafe/digisafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from protocol.views import ProtocolAutocompleteJsonView, protocol_download_file, protocol_download_sign_file
from users.views import CheckExistObjJsonView

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='home')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('accounts/', include(('account.urls', 'accounts'), namespace='accounts')),
    path('company/', include(('companies.urls', 'companies'), namespace='companies')),
    path('institutions/', include(('institutions.urls', 'institutions'), namespace='institutions')),
    path('maps/', include(('maps.urls', 'maps'), namespace='maps')),
    path('jobs/', include(('job.urls', 'job'), namespace='job')),
    path('pricelist/', include(('pricelist.urls', 'job'), namespace='pricelist')),

    path('admin/autocomplete_check_field/', CheckExistObjJsonView.as_view()), #completamento automatico del campo
    path('admin/', admin.site.urls),

    path('tinymce/', include('tinymce.urls')),  # WYSIWYG editor

    path('countries/', include('countries.urls')),
    path('protocol/', include('protocol.urls')),
    path('document/<str:path>/', protocol_download_file, name="protocol-download-file"),
    path('signs/<str:path>/', protocol_download_sign_file, name="protocol-sign-file"),

] + static("/imgs/", document_root=settings.STATIC_ROOT / "imgs")

handler404 = 'home.views.custom_page_not_found_view'
handler500 = 'home.views.custom_error_view'
handler403 = 'home.views.custom_permission_denied_view'
handler400 = 'home.views.custom_bad_request_view'

digisafe/job/urls.py
from django.urls import path, include

from .views import job_user_info, index

urlpatterns = [
    path('<int:pk>/info/', index, name="info"),
    path('userjobinfo/', job_user_info, name="user-job-info"),
]

digisafe/agenda/models.py
from django.db import models
from django.contrib.gis.db import models as gismodel
from django.conf import settings
from django.utils.translation import gettext as _

from django.utils import translation
from functools import partial
from geopy.geocoders import Nominatim
from companies.models import DateBook

from maps import gisfields


class AgendaFeatures(gismodel.Model):
    user = gismodel.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    default_position = gismodel.PointField()

    def __str__(self):
        return "{} {} - Default position: {}".format(
            self.user.last_name, self.user.first_name, self.pos_name
        )

    @property
    def pos_name(self):
        # print("account.models.AgendaFeatures.pos_name")
        user_agent = "https://nominatim.openstreetmap.org/"
        geolocator = Nominatim(user_agent=user_agent)
        lang = translation.get_language()
        reverse = partial(geolocator.reverse, language="{}".format(lang))
        try:
            location = reverse("{lat}, {lon}".format(lat=self.default_position.y, lon=self.default_position.x))
            city = location.raw.get('address').get("city")
            country = location.raw.get('address').get("country")
            return "{} ({})".format(city, country)
        except:
            return ""


class Agenda(gismodel.Model):
    user = gismodel.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    timestamp = gismodel.DateTimeField(auto_now=True)
    # city = gismodel.PointField()
    city = gisfields.PointField()
    busy = models.BooleanField(default=True)
    date_start = gismodel.DateTimeField()
    date_end = gismodel.DateTimeField()
    object = gismodel.CharField(max_length=100, default="", blank=False)
    description = gismodel.TextField(max_length=500, default="", blank=True)
    datebook = models.ForeignKey(DateBook, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "Agenda Events: {} {}/{}".format(self.object, self.date_start.date(), self.date_end.date())

    def jobs(self):
        return [x.title for x in self.user.jobprofile.job.all()]

    def date_start_date(self):
        # print("account.models.Agenda.date_start_date", self.date_start.date())
        return self.date_start.date()

    def date_end_date(self):
        return self.date_end.date()

    def marker_info(self):
        return _("<b>{}</b> <br><b>{}</b> <br>Busy from {} to {}".format(self.user.first_name, self.object, self.date_start.strftime("%d-%m-%Y"), self.date_end.strftime("%d-%m-%Y")))

    def date_range(self):
        return "{}/{}".format(self.date_start.date(), self.date_end.date())

    @property
    def city_name(self):
        # print("account.models.Agenda.city_name")
        user_agent = "https://nominatim.openstreetmap.org/"
        geolocator = Nominatim(user_agent=user_agent)
        lang = translation.get_language()
        reverse = partial(geolocator.reverse, language="{}".format(lang))
        try:
            location = reverse("{lat}, {lon}".format(lat=self.city.y, lon=self.city.x))
            city = location.raw.get('address').get("city")
            country = location.raw.get('address').get("country")
            return "{} ({})".format(city, country)
        except:
            return ""

digisafe/agenda/views.py
from django.shortcuts import render

# Create your views here.

digisafe/agenda/templates/agenda/agenda_confirm_delete.html
{% extends "home/home_base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
<form method="post">{% csrf_token %}
    <p>{% translate "Are you sure you want to delete this object?" %} : <span class="fw-bold">{{object}}</span></p>
    {{ form }}
    <input type="submit" value="{% translate 'Confirm' %}">
</form>
</div>
{% endblock %}

digisafe/agenda/templates/agenda/agenda_form.html
{% extends "home/home_base.html" %}
{% load i18n leaflet_tags geojson_tags %}

{% block extrascript %}
{% leaflet_css  %}
{% leaflet_js  %}
{{block.super}}
{{ form.media }}
<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/tomik23/autocomplete@1.8.3/dist/css/autocomplete.min.css"/>
<script src="https://cdn.jsdelivr.net/gh/tomik23/autocomplete@1.8.3/dist/js/autocomplete.min.js"></script>

<!-- Plugin Leaflet.Autocomplete -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock %}


{% block extrastyle %}
{{block.super}}
<style>

    .leaflet-container {  /* all maps */
        //width:  600px;
        height: 400px;
    }

    /* Resize the "display_raw" textbox */
    .django-leaflet-raw-textarea {
        width: 100%;
    }

    /* custom style map */
    #id_city_div_map{
        float: none !important;
    }
</style>
{% endblock %}

{% block content %}
<div class="">
    <div class="auto-search-wrapper">
        <input
        type="text"
        autocomplete="off"
        id="search"
        class="full-width"
        placeholder="{% translate 'Enter the city name' %}"
        />
    </div>
    <form method="post">{% csrf_token %}
        <fieldset {% if form.instance.datebook %}disabled{% endif %}>
            {{ form.as_p }}
        </fieldset>

        {% if form.instance.datebook %}
        <p class="fw-bold"><mark>Work session booked date</mark></p>
        <a class="btn btn-danger" href="{% url 'companies:sessionbook-bookresponse' form.instance.datebook.session.id %}?uuid={{form.instance.datebook.session.uuid}}">{% translate 'Modify booking' %}</a>
        {% else %}
        <input type="submit" class="btn btn-primary" value="{% translate 'Save' %}">
            {% if item.id %}
                <a id="delete_button" class="btn btn-danger" href="{% url 'account:calendar-del' item.id %}">{% translate 'Delete' %}</a>
            {% endif %}
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'account:calendar-set' year month %}">{% translate 'Cancel' %}</a>
    </form>

</div>
<script>
  // datetimepicker
  $(function () {
    $("input#datatimepicker").datetimepicker({
      //format: 'd/m/Y H:i',
      format: 'Y-m-d H:i',
      //format: 'd-m-Y H:i',
    });
  });
</script>
<script>
/* Definisce le costanti per il widget map */
const widget_map = geodjango_city;
//const map = geodjango_city.map;

</script>
<script type="text/javascript">
/* script per la ricerca del luogo e centraggio della mappa */
// minimal configure
new Autocomplete("search", {
  // default selects the first item in
  // the list of results
  selectFirst: true,

  // The number of characters entered should start searching
  howManyCharacters: 2,

  // onSearch
  onSearch: ({ currentValue }) => {
    // You can also use static files
    // const api = '../static/search.json'
    const api = `https://nominatim.openstreetmap.org/search?format=geojson&limit=5&city=${encodeURI(
      currentValue
    )}`;

    return new Promise((resolve) => {
      fetch(api)
        .then((response) => response.json())
        .then((data) => {
          resolve(data.features);
        })
        .catch((error) => {
          console.error(error);
        });
    });
  },
  // nominatim GeoJSON format parse this part turns json into the list of
  // records that appears when you type.
  onResults: ({ currentValue, matches, template }) => {
    const regex = new RegExp(currentValue, "gi");

    // if the result returns 0 we
    // show the no results element
    return matches === 0
      ? template
      : matches
          .map((element) => {
            return `
          <li class="loupe">
            <p>
              ${element.properties.display_name.replace(
                regex,
                (str) => `<b>${str}</b>`
              )}
            </p>
          </li> `;
          })
          .join("");
  },

  // we add an action to enter or click
  onSubmit: ({ object }) => {
    const { display_name } = object.properties;
    const [lat, lng] = object.geometry.coordinates;

    var center = [lat, lng];
    if (widget_map.options.map_srid) {
        center = ol.proj.transform(center, 'EPSG:4326', geodjango_city.map.getView().getProjection() );
    }
    widget_map.map.getView().setCenter(center);
    widget_map.map.getView().setZoom(geodjango_city.options.default_zoom);
  },

  // get index and data from li element after
  // hovering over li with the mouse or using
  // arrow keys ↓ | ↑
  onSelectedItem: ({ index, element, object }) => {
    //console.log("onSelectedItem:", index, element, object);
  },

  // the method presents no results element
  noResults: ({ currentValue, template }) =>
    template(`<li>No results found: "${currentValue}"</li>`),
});
</script>
{% endblock %}