digisafe/companies/urls.py
from django.urls import path, include

from .views import home, set_company
from .views import companyDetailView, companyPublicDetailView, requestAssociateToUser, requestAssociateToCompany
from .views import requestAssociateAction, retrieve_users_to_associate, requestDissociateAction
from .views import favoriteuser, list_users_from_map, retrive_users_from_map, book_user
from .views import SessionBookCreateView, SessionBookListView, SessionBookUpdateView, SessionBookDetailView,\
                    SessionBookDeleteView, openMap, send_invite_now, SettingsCompanyView, sessionBookUsers

urlpatterns = [
    path('home/', home, name="home"),
    path('<int:pk>/set/', set_company, name="set-company"),
    path('settings/', SettingsCompanyView.as_view(), name="setting"),

    path('<int:pk>/view/', companyDetailView, name="company-view"),
    path('<int:pk>/public/view/', companyPublicDetailView, name="company-public-view"),
    path('associateuser/', requestAssociateToUser, name="company-request-user"),
    path('<int:pk>/dissociateuseraction/', requestDissociateAction, name="company-dissociate-user"),
    path('associateuseraction/', requestAssociateAction, name="company-request-user-action"),
    path('associatecompany/', requestAssociateToCompany, name="user-request-company"),
    path('users/search/', retrieve_users_to_associate, name="company-user-search"),

    # map
    path('openmap/book/<int:session_id>/view/', openMap, name="openmap"),
    path('openmap/book/<int:session_id>/optionlist/', list_users_from_map, name="optionusers"),
    path('openmap/book/<int:session_id>/retriveoptionlist/', retrive_users_from_map, name="retriveoptionlist"),
    path('openmap/book/<int:session_id>/invite/', send_invite_now, name="send-invite"),

    path('favoriteuser/', favoriteuser, name="favoriteuser"),
    path('bookuser/', book_user, name="bookuser"),

    # work session
    path('sessionbook/list/', SessionBookListView.as_view(), name="sessionbook-list"),
    path('sessionbook/create/', SessionBookCreateView.as_view(), name="sessionbook-create"),
    path('sessionbook/<int:pk>/update/', SessionBookUpdateView.as_view(), name="sessionbook-update"),
    path('sessionbook/<int:pk>/delete/', SessionBookDeleteView.as_view(), name="sessionbook-delete"),
    # path('sessionbook/<int:pk>/detail/', SessionBookDetailView.as_view(), name="sessionbook-detail"),
    path('sessionbook/<int:pk>/bookresponse/', SessionBookDetailView.as_view(), name="sessionbook-bookresponse"),
    path('sessionbook/<int:pk>/users/', sessionBookUsers, name="sessionbook-users"),

]

digisafe/digisafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from protocol.views import ProtocolAutocompleteJsonView, protocol_download_file, protocol_download_sign_file
from users.views import CheckExistObjJsonView

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='home')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('accounts/', include(('account.urls', 'accounts'), namespace='accounts')),
    path('company/', include(('companies.urls', 'companies'), namespace='companies')),
    path('institutions/', include(('institutions.urls', 'institutions'), namespace='institutions')),
    path('maps/', include(('maps.urls', 'maps'), namespace='maps')),
    path('jobs/', include(('job.urls', 'job'), namespace='job')),
    path('pricelist/', include(('pricelist.urls', 'job'), namespace='pricelist')),

    path('admin/autocomplete_check_field/', CheckExistObjJsonView.as_view()), #completamento automatico del campo
    path('admin/', admin.site.urls),

    path('tinymce/', include('tinymce.urls')),  # WYSIWYG editor

    path('countries/', include('countries.urls')),
    path('protocol/', include('protocol.urls')),
    path('document/<str:path>/', protocol_download_file, name="protocol-download-file"),
    path('signs/<str:path>/', protocol_download_sign_file, name="protocol-sign-file"),

] + static("/imgs/", document_root=settings.STATIC_ROOT / "imgs")

handler404 = 'home.views.custom_page_not_found_view'
handler500 = 'home.views.custom_error_view'
handler403 = 'home.views.custom_permission_denied_view'
handler400 = 'home.views.custom_bad_request_view'

digisafe/job/urls.py
from django.urls import path, include

from .views import job_user_info, index

urlpatterns = [
    path('<int:pk>/info/', index, name="info"),
    path('userjobinfo/', job_user_info, name="user-job-info"),
]

digisafe/companies/models.py
from django.db import models
from django.contrib.gis.db import models as gismodel
from django.urls import reverse
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db.models import Sum, Count
from django.utils import timezone
from django.utils.translation import gettext as _
import os
import uuid

from maps import gisfields
from digisafe import storage
from users.models import User
from countries.models import Country, City
from job.models import Job


class Company(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    active = models.BooleanField(default=True)
    admins = models.ManyToManyField(
                User,
                blank=True,
                related_name="admins_company"
            )
    associates = models.ManyToManyField(
                User,
                blank=True,
                related_name="associates_company"
            )

    favorite = models.ManyToManyField(
                User,
                blank=True,
                related_name="favorite_company"
            )

    def __str__(self):
        return "{0}".format(self.name)

    def list_admins(self):
        from django.utils.safestring import mark_safe
        res = ["{0} {1}<br>".format(x.last_name.upper() , x.first_name.upper() ) for x in self.admins.all()]
        html = "".join(res)
        return mark_safe(html)

    def list_favorite(self):
        from django.utils.safestring import mark_safe
        res = ["{0} {1}<br>".format(x.last_name.upper() , x.first_name.upper() ) for x in self.favorite.all()]
        html = "".join(res)
        return mark_safe(html)


def file_path_name_company(instance, file_name):
    prefix = "logo_company"
    file_root, file_ext = os.path.splitext(file_name)
    return "{}_{}_{}".format(prefix, instance.id, file_ext)


class Profile(models.Model):
    company = models.OneToOneField(
                        Company,
                        on_delete=models.CASCADE,
                    )
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
        null=True,
        # blank=True
        verbose_name=_("country")
    )
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        null=True,
        # blank=True
        verbose_name=_("city")
    )
    address = models.CharField(max_length=255)
    desc = models.TextField(default="", verbose_name=_("description"))
    logo = models.FileField(
                    upload_to=file_path_name_company,
                    storage=storage.FileSystemStorage(location='static/imgs/', base_url="/imgs"),
                    validators=[storage.validate_file_size, storage.validate_file_extension_img],
                  )

    def __str__(self):
        return "{}".format(self.company.name)


class requestAssociatePending(models.Model):
    user = models.ForeignKey(
                User,
                on_delete=models.CASCADE,
                blank=True,
            )
    company = models.ForeignKey(
                Company,
                on_delete=models.CASCADE,
                blank=True,
            )
    user_req    = models.BooleanField(default=False)
    company_req = models.BooleanField(default=False)


# * Booking Models START * #


class SessionBook(gismodel.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    city = gisfields.PointField()
    note = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    expire_date = models.DateTimeField()
    jobs = models.ManyToManyField(Job)
    user_option_list = models.ManyToManyField(User, blank=True)
    user_decline_list = models.ManyToManyField(User, related_name="sessionbook_user_decline", blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return "{}".format(self.name)

    def user_option_list_secure_remove(self, user):
        """
        Rimuove user dalla lista 'user_option_list' in modo sicuro.
        Rimuove solo se non presente nella lista 'user' (prenotati) di DateBook (prenotato da parte dell'utente)
         e 'users_confirm' di DateBook (confermato prenotazione da parte della company).
        :param user: User object
        :return: bool True utente correttamente rimosso dalla lista
                 str con il motivo della mancata rimozione 'User have been booked or confirmed'
        """
        # print("companies.models.SessionBook.user_option_list_secure_remove")
        if not self.datebook_set.filter(users_confirm=user) \
                and not self.datebook_set.filter(users=user) \
                and not self.user_decline_list.filter(id=user.id):
            # print("No booked and confirm and declined", "Rimuovi")
            self.user_option_list.remove(user)
            return True
        # print("booked/confirmed/declined. non rimosso")
        return "User have been booked or confirmed. Can't remove."

    def user_option_list_add(self, user):
        """
        Aggiunge un utente alla lista invitati user_option_list, se:
        - non è nella lista declinati user_decline_list
        :param user: object User
        :return: bool True if add in list
                 str message "User have been declined"
        """
        # print("companies.models.SessionBook.user_option_list_add")
        if self.declined_user(user.id):
            return "User have been declined"
        self.user_option_list.add(user)
        return True

    def user_decline_list_add(self, user):
        """
        Utente declina l'invito, se:
        - Company non ha già confermato una prenotazione
        :param user: User object
        :return: bool True: utente ha declinato, False utente non ha declinato
        """
        # print("companies.models.SessionBook.user_decline_list_add")
        if self.datebook_set.filter(session=self.id).exclude(users_confirm=user):
            self.user_decline_list.add(user)
            # Viene cancellato dalle ventuali prenotazioni
            for db in self.datebook_set.all():
                db.users.remove(user)
                db.users_confirm.remove(user)
            # Cancellare tutte le date in agenda (siccome declina anche con date prenotate)
            user.agenda_remove_sessionbook(self)

            # todo: notifica alla company l'azione di declino
            return True
        return False

    def range_date(self):
        """
        Range delle date della work session
        :return: str
        """
        return "{}/{}".format(self.start_date, self.end_date)

    def send_book_invite(self):
        """
        Invia una email di invito agli utenti nella lista invitati.
        Usa il metodo 'sendSystemEmail' di User.
        :return: None
        """
        # print("companies.models.SessionBook.send_book_invite")
        date_list = [x.date.strftime("%d-%m-%Y") for x in self.datebook_set.all()]
        dates = "\n".join(date_list)
        for u in self.user_option_list.all():

            subject = "Invite book session from {}. Open until date {}".format(self.company, self.expire_date.date())
            msg =""" 
Dear {username},

You have been invited to book on work session id {session_id}

Session name: {session_name}
Address: {address}
Expiration date: {exp_date}

Work session dates:
{dates}

Link to choose the date
{url_choice_dates}?uuid={uuid}

            """.format(
                session_id=self.id,
                username=u.getFullName,
                url_choice_dates=settings.HTTP+settings.CURRENT_SITE+reverse(
                    "companies:sessionbook-bookresponse",
                    args=[self.id]
                ),
                uuid=self.uuid,
                session_name=self.name,
                address=self.address,
                exp_date=self.expire_date.date(),
                dates=dates,
            )
            u.sendSystemEmail(subject, msg)

    def total_users_request(self):
        """
        Numero totale di utenti richiesti nella work session.
        Somma le giornate con il numero di operatori richiesti per ogni giornata
        :return: int
        """
        return self.datebook_set.aggregate(Sum("number_user"))["number_user__sum"]

    def total_users_booked(self):
        """
        Numero totale di utenti prenotati
        :return: int
        """
        return self.datebook_set.aggregate(Count("users"))["users__count"]

    def total_users_confirmed(self):
        """
        Numero totale di utenti confermati
        :return: int
        """
        return self.datebook_set.aggregate(Count("users_confirm"))["users_confirm__count"]

    def is_expired(self):
        """
        Controlla se ha superato la data di scadenza per le prenotazioni
        :return: bool
        """
        return timezone.now() > self.expire_date

    def is_full(self):
        """
        Verifica se una work session è al completo
        :return: bool
        """
        for db in self.datebook_set.all():
            if db.number_user != db.users_confirm.count():
                return False
        return True

    def declined_user(self, user_id):
        """
        Cerca un utente nella lista dei declinati
        :param user_id:
        :return: QuerySet object
        """
        return self.user_decline_list.filter(pk=user_id)

    def declined_users(self):
        """
        Lista utenti che hanno declinato
        :return: QuerySet object
        """
        return self.user_decline_list.all()

    def invited_user(self, user_id):
        """
        Cerca un utente nella lista invitati 'user_option_list'
        :param user_id: pk object User
        :return: QuerySet list object
        """
        return self.user_option_list.filter(pk=user_id)

    def invited_users(self):
        """
        Lista utenti invitati
        :return: QuerySet list object
        """

digisafe/companies/templates/companies/index.html
{% extends "companies/index_base.html" %}
{% load i18n static %}

{% block content %}
<DIV class="container m-2">
<h1 class="bg-primary text-white fs-1 p-2">{{company.name}}</h1>
<h3 class="bg-primary bg-opacity-25 text-dark fs-3 p-2">{% translate 'Dashboard panel' %}</h3>

    <nav>
        <ul class="nav nav-tabs" id="nav-admin-tab" role="tablist">
            <li>
                <button class="nav-link "       id="nav-listusers-tab" data-bs-toggle="tab" data-bs-target="#nav-listusers" type="button" role="tab" aria-controls="nav-listusers" aria-selected="true" >{% translate 'Associate users' %}</button>
            </li>
            <li>
                <button class="nav-link "       id="nav-associate-tab" data-bs-toggle="tab" data-bs-target="#nav-associate" type="button" role="tab" aria-controls="nav-associate" aria-selected="false">{% translate 'Seacrh users' %}</button>
            </li>
            <li>
                <a class="nav-link" href="{% url 'companies:sessionbook-list' %}">Session list</a>
            </li>
        </ul>
    </nav>
    <div class="tab-content" id="nav-admin-tabContent">
      <div class="tab-pane fade " id="nav-associate" role="tabpanel" aria-labelledby="nav-associate-tab">
        <div class="m-3">
        <h1 class="fw-bold">{% translate 'Users available' %}</h1>
        {% include 'companies/user_to_associate.html' %}
        </div>

      </div>
      <div class="tab-pane fade" id="nav-listusers" role="tabpanel" aria-labelledby="nav-listusers-tab">
        <div class="m-3">
        <h1  class="fw-bold">{% translate 'Associate users' %}</h1>
        {% include 'companies/associate_user.html' %}
        </div>
      </div>
    </div>
</DIV>


{% endblock %}

digisafe/companies/templates/companies/index_base.html
{% extends "home/home_base.html" %}
{% load i18n static %}


{% block nav-bar-sub-brand %}
    <span class="navbar-brand text-black fw-bold">
        {% if request.session.company_name %}
        {{request.session.company_name}}
        {% else %}
        {% translate "Company" %}
        {% endif %}

    </span>
{% endblock %}
{% block nav-bar-sub-content %}
<div class="navbar-nav me-auto mb-2 mb-lg-0">
    {% if user.profile.administrator %}
    <a class="nav-link" href="{% url 'companies:home' %}"><i class="bi bi-building"></i> {% translate "Select" %}</a>
    {% endif %}
    {% if request.session.company_id %}
    <a class="nav-link" href="{% url 'companies:setting' %}"><i class="bi bi-gear"></i> {% translate "Settings" %}</a>
    <a class="nav-link" href="{% url 'companies:sessionbook-list' %}"><i class="bi bi-map"></i> {% translate "Sessions" %}</a>
    {% endif %}
</div>
{% endblock %}

digisafe/companies/templates/companies/overlays.html
var lc = map.layerscontrol;

// An example from the Atlas of Living Australia https://www.ala.org.au/
lc.addOverlay(
    L.tileLayer.wms(
    'https://spatial-beta.ala.org.au/geoserver/ALA/wms',
    {layers: 'ALA:aus2', format: 'image/png', transparent: true}),
    'Australia'
);

// add lc.addOverlay() layers as needed

digisafe/companies/templates/companies/select.html
{% extends "companies/index_base.html" %}
{% load i18n static %}

{% block content %}
<div>
      <h1 class="">{% translate 'Dashboard Companies' %}</h1>
      <div class="">
        <p>{% translate 'Managed companies' %}</p>
            {% for company in company_list %}
                <div class="m-3">
                <a href="{% url 'companies:set-company' company.id %}" class="btn btn-primary">{% translate 'Select' %}</a> {{company.name}}
                </div>
          {% endfor %}
      </div>
</div>
{% endblock %}

digisafe/companies/templates/companies/sessionbook_form.html
{% extends "companies/index_base.html" %}
{% load i18n static %}

{% block extrascript %}
{% endblock %}

{% block admin_django_css_ %}
{% endblock %}

{% block content %}
    {{form.media}}
    <div class="container my-2">
        {# BOTTONI MAPPA E MODIFICA #}
        {% if form.instance.id %}
        <div class="submit-row float-end  p-1 border rounded">
            <a href="{% url 'companies:sessionbook-users' form.instance.id %}" class="btn btn-info  "  data-bs-toggle="tooltip"
                   data-bs-placement="top" title="Users booked"><i class="bi bi-person-lines-fill"></i></a>
            <a href="{% url 'companies:openmap' form.instance.id %}" class="btn btn-info  "  data-bs-toggle="tooltip"
                   data-bs-placement="top" title="Open map"><i class="bi bi-map-fill"></i></a>
        </div>
        {% endif %}
        <h1>SESSION BOOK FORM {{form.instance.id}}</h1>
        <div>
            <form class="" method="post">{% csrf_token %}
                <div>
                    {{ form.as_p }}
                </div>
                {% if dates_form %}
                <h2>Modifica numero operatori richiesti per ogni data</h2>
                {% endif %}
                {{ dates_form.management_form }}
                {% for df in dates_form %}
                <div class="row align-items-center">
                    {{ df.id }}
                    <div class="col mb-1">
                        <div class="p-1 border bg-light">
                            <label class="text-uppercase float-start">{{df.job.label}}</label>
                            <p class="text-center">{{ df.instance.job }}</p>
                        </div>
                    </div>
                    <div class="col mb-1 ">
                        <div class="p-1 border bg-light">
                            <label class="text-uppercase float-start">{{df.date.label}}</label>
                            <p class="text-center">{{ df.instance.date }}</p>
                        </div>
                    </div>
                    <div class="col  mb-1">
                        <div class="p-1 border bg-light">
                            <label  class="text-uppercase float-start">{{ df.number_user.label }}</label>
                            <p class="text-center m-0 p-0">{{ df.number_user }}</p>
                        </div>
                    </div>

                </div>

                {% endfor %}
                <div class="submit-row">
                    <input type="submit" value="Save" name="save_close" class="default">
                    <input type="submit" value="Save and modify" name="save_modify" class="">
                    <a href="{% url 'companies:sessionbook-list' %}" class="closelink">Annulla</a>
                </div>
            </form>
        </div>
    </div>

<script type="text/javascript">
    var jQuery = $;
    window.addEventListener('load', function(e) {
        SelectFilter.init("id_jobs", "jobs", 0, "/static/admin/");
        jQuery(".selector").css("float", "none");
        jQuery("form p").addClass("clearfix");
    });
</script>

{% endblock %}

digisafe/companies/templates/companies/sessionbook_list.html
{% extends "companies/index_base.html" %}
{% load i18n static %}

{% block content %}
<div class="">
    <div>
        <h1>{% translate "Book sessions list" %}</h1>
    </div>

    {# RICERCA #}
    <div>
        <form method="get">
            <div class="input-group mb-3">
                <input type="text" class="form-control" id="floatingInputValue" placeholder="{% translate 'Search by name and notes' %}"
                       aria-label="Ricerca per nome e note" aria-describedby="search"
                       value="{{request.GET.qs}}" name="qs">
                <button id="search" type="submit" class="btn btn-outline-primary"><i class="bi bi-search"></i></button>
            </div>
        </form>
    </div>

    {# ADD SESSION #}
    <div class="my-2">
        <a class="btn btn-success bi-plus-circle-fill" href="{% url 'companies:sessionbook-create' %}">
            {% translate "New session" %}</a>
    </div>

    {# HEAD GRIGLIA #}
    <div class="row  d-none d-lg-block g-1">
    <div class="row g-1">
        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">{% translate "Actions" %}</p>
        </div>

        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">
                <i class="bi bi-bookmark"></i> {% translate "Work session" %}</p>
        </div>
        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">
                <i class="bi bi-calendar-x"></i> {% translate "Expire date" %}</p>
        </div>
        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">
                <i class="bi bi-calendar-range"></i> {% translate "Start/End dates" %}</p>
        </div>
        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">
                <i class="bi bi-card-text"></i> {% translate "Notes" %}</p>
        </div>

        <div class="col ">
            <p class=" fw-bold text-white bg-secondary text-center">{% translate "Overview" %}</p>
        </div>
    </div>
    </div>

    {# BODY COLONNE GRIGLIA #}
    {% for sb in sessionbook_list %}
    <div class="row mb-3 mb-lg-2 pb-1 g-1 border-bottom alert-secondary">
        <div class="col-md">
            <div class="overflow-scroll" style="max-height: 8rem;">
                <span class="text-break">{{sb.name}}</span>
            </div>
        </div>
        <div class="col">
            <div class="overflow-scroll" style="max-height: 8rem;">
                {{sb.expire_date}}
            </div>
        </div>
        <div class="col">
            <div><i class="bi bi-align-start"></i> {{sb.start_date}} <br>
                 <i class="bi bi-align-end"></i> {{sb.end_date}}</div>
        </div>
        <div class="col-lg">
            <div class="overflow-scroll" style="max-height: 8rem;" ><span class="text-break">{{sb.note}}</span></div>
        </div>
        <div class="col m-0 p-0 border rounded p-0 m-0 align-self-start">
            <div class="text-center d-grid gap-0">
                <a class="btn btn-outline-primary btn-sm m-0 p-0 width-100" href="{% url 'companies:sessionbook-users' sb.id %}">
                    <i class="float-start bi bi-person-lines-fill"></i>
                    <span class=""> {% translate "Manage" %} </span>
                </a>
            </div>
            <div class="row text-center p-0 m-0 mt-1 mx-2 mx-lg-0 alert-info">
                <div class="col "data-bs-toggle="tooltip" title="Resources"><i class="bi bi-person"></i> {{sb.total_users_request}}</div>
                <div class="col "data-bs-toggle="tooltip" title="Dates"><i class="bi bi-calendar3-week"></i> {{sb.datebook_set.all|length}}</div>
                <div class="col "data-bs-toggle="tooltip" title="Jobs"><i class="bi bi-briefcase"></i> {{sb.jobs.all|length}}</div>
            </div>
            <div class="row row-cols-2  p-0 m-0 mt-1">
                <div class="col  m-0 p-0 pe-1 text-truncate">
                    <span class="badge bg-secondary">{{sb.user_option_list.all|length}}</span>
                    <span class="text-truncate">{% translate "Invited" %}</span> </div>
                <div class="col m-0 p-0 ps-1 text-danger text-truncate">
                    <span class="badge bg-danger ">{{sb.user_decline_list.all|length}}</span>
                    <span class="text-truncate">{% translate "Declined" %}</span> </div>
                <div class="col m-0 p-0 pe-1 text-danger text-truncate">
                    <span class="badge bg-primary">{{sb.total_users_booked}}</span>
                    <span class="">{% translate "Booked" %}</span> </div>
                <div class="col m-0 p-0 ps-1 text-danger text-truncate">
                    <span class="badge bg-success">{{sb.total_users_confirmed}}</span>
                    <span class="">{% translate "Confirmed" %}</span> </div>
            </div>
            {% if sb.is_full %}<div class="text-center my-1 alert-success border border-success"><i class="bi bi-clipboard-check"></i> Full</div>{% endif %}
        </div>
        <div class="col-lg order-lg-first text-center">
                <a href="{% url 'companies:openmap' sb.id %}" class="btn btn-info  "  data-bs-toggle="tooltip"
                   data-bs-placement="top" title="Open map"><i class="bi bi-map-fill"></i></a>
                <a href="{% url 'companies:sessionbook-update' sb.id %}" class="btn btn-success  "
                   data-bs-toggle="tooltip" data-bs-placement="top" title="Update Session"><i class="bi bi-pencil-fill"></i></a>
                <a href="{% url 'companies:sessionbook-delete' sb.id %}" class="btn btn-danger  "
                   data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"><i class="bi bi-trash-fill"></i></a>
        </div>
    </div>
    {% endfor %}

    {# IMPAGINAZIONE #}
    <div class="mt-3 text-center fs-4">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="bi-skip-backward-fill"></a>
                <a href="?page={{ page_obj.previous_page_number }}" class="bi-caret-left-fill"></a>
            {% endif %}

            <span class="current">
                {% translate "Page" %} {{ page_obj.number }} {% translate "of" %} {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="bi-caret-right-fill"></a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="bi-skip-forward-fill"></a>
            {% endif %}
        </span>
    </div>

</div>
{% endblock %}

digisafe/companies/templates/companies/user_to_associate.html
{% load i18n static %}

<div class="container">
    <div class="" >
      <form class="row g-3" onsubmit="search_user">
        <label for="user" class="col-sm-2 col-form-label">{% translate "User" %}</label>
        <div class="col-sm-4">
            <input type="text" class="form-control-plaintext" id="user" value="">
        </div>
        <div class="col-auto">
            <button type="submit" id="search_button" class="btn btn-primary mb-3">{% translate "Search" %}</button>
        </div>
      </form>
    </div>
    <div class="head fw-bold">
        <div class="row">
            <div class="col">{% translate "User" %}</div>
            <div class="col">{% translate "Info" %}</div>
            <div class="col-2">{% translate "Associate" %}</div>
        </div>
    </div>
    <div class="body" id="body_result">

    </div>

</div>
<script>
window.onload = function() {
    document.getElementById('search_button').addEventListener('click', search_user);
    function response_from_html(response){
        var body = document.getElementById('body_result');
        body.innerHTML = response;
        $("button#user_click").each(function(el){
            //console.log(el);
            $(this).click(function(e) {
                //console.log( $(this) );
                var that = this;
                var user_id = $(this).attr("user_id");
                url = "{% url 'companies:company-request-user' %}";
                var data = {};
                data["user_id"] = user_id;
                $.ajax({
                    type: 'GET',
                    dataType:'json',
                    url: url,
                    data: data,
                    success: function (response) {
                        // on successfull creating object
                        //console.log(response);
                        if (response.save == 'ok'){
                            $(that).attr("disabled");
                            $(that).addClass("disabled");
                            $(that).text("{% translate 'Pending...' %}");
                            console.log("disabled")
                        }
                        // response_from_html(response);
                    },
                    error: function (response) {
                        // alert the error if any error occured
                        console.log("error ajax: ", response);
                        //var body = document.getElementById('body_result');
                        // body.innerHTML = "Errore nella richiesta";
                    }
                });
            });
        })
        
    }
    
    function search_user(e){
        //console.log("search_user");
        e.preventDefault();
        var slug = document.getElementById('user').value;
        var url = "{% url 'companies:company-user-search' %}";
        var data = {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    slug: slug,
            }
        $.ajax({
            type: 'POST',
            // dataType:'json',
            url: url,
            data: data,
            success: function (response) {
                // on successfull creating object
                // console.log(response);
                response_from_html(response);
            },
            error: function (response) {
                // alert the error if any error occured
                console.log("error ajax: ", response);
                var body = document.getElementById('body_result');
                body.innerHTML = "Errore nella richiesta";
            }
        });
    }
    
    
}

</script>