digisafe/account/urls.py
from django.urls import path, include

from .views import accountView, logoutView, loginView, loginLostView, \
    changePasswordView, resetPasswordView, setPosition, certificateView, \
    dissociateCompanyView, searchCourseView, calendarView, CalendarDelEventView, \
    CalendarFormEventView, CalendarAddView, coursesView, indexView, SettingsView, \
    WorkSessionView


urlpatterns = [
    path('', indexView, name="index"),
    path('courses/', coursesView, name="courses"),
    path('settings/<int:pk>/', SettingsView.as_view(), name="settings"),
    path('agenda/view/', calendarView, name="calendar"),
    path('agenda/set/<int:year>/<int:month>/', calendarView, name="calendar-set"),
    path('agenda/add/<int:year>/<int:month>/<int:day>/', CalendarAddView.as_view(), name="calendar-add"),
    path('agenda/edit/<int:pk>/date/<int:year>/<int:month>/<int:day>/',
         CalendarFormEventView.as_view(), name="calendar-edit"),
    path('agenda/del/<int:pk>/', CalendarDelEventView.as_view(), name="calendar-del"),

    path('company/<int:pk>/dissociate/', dissociateCompanyView, name="dissociate"),
    path('login/', loginView, name="login"),
    path('logout/', logoutView, name="logout"),
    path('loginlost/', loginLostView, name="login-lost"),
    path('changepassword/', changePasswordView, name="change-password"),
    path('resetpassword/', resetPasswordView, name="reset-password"),
    path('user/setposition', setPosition, name="setposition"),
    path('protocol/<int:pk_protocol>/view/', certificateView, name="view-certificate"),
    path('searchcourse/', searchCourseView, name="searchcourse"),

    # work session book
    path('worksessions/', WorkSessionView.as_view(), name="worksessions"),
]

digisafe/companies/urls.py
from django.urls import path, include

from .views import home, set_company
from .views import companyDetailView, companyPublicDetailView, requestAssociateToUser, requestAssociateToCompany
from .views import requestAssociateAction, retrieve_users_to_associate, requestDissociateAction
from .views import favoriteuser, list_users_from_map, retrive_users_from_map, book_user
from .views import SessionBookCreateView, SessionBookListView, SessionBookUpdateView, SessionBookDetailView,\
                    SessionBookDeleteView, openMap, send_invite_now, SettingsCompanyView, sessionBookUsers

urlpatterns = [
    path('home/', home, name="home"),
    path('<int:pk>/set/', set_company, name="set-company"),
    path('settings/', SettingsCompanyView.as_view(), name="setting"),

    path('<int:pk>/view/', companyDetailView, name="company-view"),
    path('<int:pk>/public/view/', companyPublicDetailView, name="company-public-view"),
    path('associateuser/', requestAssociateToUser, name="company-request-user"),
    path('<int:pk>/dissociateuseraction/', requestDissociateAction, name="company-dissociate-user"),
    path('associateuseraction/', requestAssociateAction, name="company-request-user-action"),
    path('associatecompany/', requestAssociateToCompany, name="user-request-company"),
    path('users/search/', retrieve_users_to_associate, name="company-user-search"),

    # map
    path('openmap/book/<int:session_id>/view/', openMap, name="openmap"),
    path('openmap/book/<int:session_id>/optionlist/', list_users_from_map, name="optionusers"),
    path('openmap/book/<int:session_id>/retriveoptionlist/', retrive_users_from_map, name="retriveoptionlist"),
    path('openmap/book/<int:session_id>/invite/', send_invite_now, name="send-invite"),

    path('favoriteuser/', favoriteuser, name="favoriteuser"),
    path('bookuser/', book_user, name="bookuser"),

    # work session
    path('sessionbook/list/', SessionBookListView.as_view(), name="sessionbook-list"),
    path('sessionbook/create/', SessionBookCreateView.as_view(), name="sessionbook-create"),
    path('sessionbook/<int:pk>/update/', SessionBookUpdateView.as_view(), name="sessionbook-update"),
    path('sessionbook/<int:pk>/delete/', SessionBookDeleteView.as_view(), name="sessionbook-delete"),
    # path('sessionbook/<int:pk>/detail/', SessionBookDetailView.as_view(), name="sessionbook-detail"),
    path('sessionbook/<int:pk>/bookresponse/', SessionBookDetailView.as_view(), name="sessionbook-bookresponse"),
    path('sessionbook/<int:pk>/users/', sessionBookUsers, name="sessionbook-users"),

]

digisafe/digisafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from protocol.views import ProtocolAutocompleteJsonView, protocol_download_file, protocol_download_sign_file
from users.views import CheckExistObjJsonView

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='home')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('accounts/', include(('account.urls', 'accounts'), namespace='accounts')),
    path('company/', include(('companies.urls', 'companies'), namespace='companies')),
    path('institutions/', include(('institutions.urls', 'institutions'), namespace='institutions')),
    path('maps/', include(('maps.urls', 'maps'), namespace='maps')),
    path('jobs/', include(('job.urls', 'job'), namespace='job')),
    path('pricelist/', include(('pricelist.urls', 'job'), namespace='pricelist')),

    path('admin/autocomplete_check_field/', CheckExistObjJsonView.as_view()), #completamento automatico del campo
    path('admin/', admin.site.urls),

    path('tinymce/', include('tinymce.urls')),  # WYSIWYG editor

    path('countries/', include('countries.urls')),
    path('protocol/', include('protocol.urls')),
    path('document/<str:path>/', protocol_download_file, name="protocol-download-file"),
    path('signs/<str:path>/', protocol_download_sign_file, name="protocol-sign-file"),

] + static("/imgs/", document_root=settings.STATIC_ROOT / "imgs")

handler404 = 'home.views.custom_page_not_found_view'
handler500 = 'home.views.custom_error_view'
handler403 = 'home.views.custom_permission_denied_view'
handler400 = 'home.views.custom_bad_request_view'

digisafe/home/urls.py
from django.urls import path, include

from .views import home


urlpatterns = [
    path('', home, name="index"),
    
]

digisafe/job/urls.py
from django.urls import path, include

from .views import job_user_info, index

urlpatterns = [
    path('<int:pk>/info/', index, name="info"),
    path('userjobinfo/', job_user_info, name="user-job-info"),
]

digisafe/home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

def home(request):
    return render(request, "home/index.html")

def custom_page_not_found_view(request, exception):
    return render(request, "home/errors/404.html", {})

def custom_error_view(request, exception=None):
    return render(request, "home/errors/500.html", {})

def custom_permission_denied_view(request, exception=None):
    return render(request, "home/errors/403.html", {})

def custom_bad_request_view(request, exception=None):
    return render(request, "home/errors/400.html", {})

digisafe/home/templates/home/base.html
{% load i18n static compress %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:'en-us' }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {# Theme CSS Bootstrap #}
    {% compress css %}
    <link type="text/x-scss" href="{% static 'theme.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}

    {# CSS Admin #}
    {% block admin_django_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
    {% endblock %}

    {# BOOTSTRAP #}
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <script src="{% static 'js/jquery/jquery.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    {# Htmx #}
<!--    <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>-->

<!-- extrascript -->
{% block extrascript %}{% endblock %}
<!-- END extrascript -->

<!-- extrastyle -->
{% block extrastyle %}{% endblock %}
<!-- END extrastyle -->

{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static 'admin/css/rtl.css' %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    {% if LANGUAGE_BIDI %}<link rel='stylesheet' type='text/css' href="{% static 'admin/css/responsive_rtl.css' %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}

</head>

<body class="">
<!-- Container -->
<div class="container-fluid px-0">
    <!-- Header -->
    {% block header %}
    <div id="header" class="m-0 p-1">
        <div id="branding" class="">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if request.user.is_authenticated %}
        <div id="user-tools" class="m-0 p-1">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
                {% get_current_language as LANGUAGE_CODE %}
                ({{ LANGUAGE_CODE }})
            {% endblock %}
            <div>
            {% block userlinks %}
                {% if site_url %}
                <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'account:change-password' %}">{% translate 'Change password' %}</a> /
                {% endif %}
                {% if user.is_staff %}
                <a href="{% url 'admin:index' %}">{% translate 'Admin' %}</a> /
                {% endif %}
                <a href="{% url 'account:logout' %}">{% translate 'Log out' %}</a>
            {% endblock %}
            </div>
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->
    
    <!-- Nav-bar-menu -->
    {# MAIN MENU #}
    <nav class="navbar navbar-expand-lg px-1 navbar-dark bg-dark">
        <div class="container-fluid fs-5">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                {% block nav-bar %}{% endblock %}
                {# LANGUAGE #}
                <div>
                    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <select name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                    {{ language.code }}
                                </option>
                            {% endfor %}
                        </select>
                        <input class="btn btn-sm p-1" type="submit" value="{% translate 'Go' %}">
                    </form>
                </div>
            </div>
        </div>
    </nav>

    {# SUB MENU #}
    {% block nav-bar-sub %}
    <nav class="navbar navbar-expand-lg px-2 bg-secondary">
        <div class="container-fluid fs-6">
            {% block nav-bar-sub-brand %}{% endblock %}
            <button class="navbar-toggler  float-end " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSubMenu" aria-controls="navbarSubMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-menu-button-fill"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSubMenu">
                {% block nav-bar-sub-content %}{% endblock %}
            </div>
        </div>
    </nav>

    {% endblock %}
    <!-- END Nav-bar -->

    {# breadcrumbs #}
    <!-- breadcrumbs -->
    {% block breadcrumbs %}{% endblock %}
    <!-- END breadcrumbs -->

    {# messages #}
    {% block messages %}
      {% if messages %}
        <div class="content">
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        </div>
      {% endif %}
    {% endblock messages %}

    {# CONTENT #}
    <div class="container-xl">
    {% block content %}
    <h1>HOME</h1>
    {% endblock %}
    </div>

    {# FOOTER #}
    {% block footer %}
    <div class="clearfix"></div>
    <div class="border-top border-secondary mt-4 py-2 alert-secondary">
        <div class="align-items-center text-center">
          <span class="text-muted">© 2021 IRCoT Group</span>
        </div>

    </div>


    {% endblock %}
</div>
</body>
</html>

digisafe/home/templates/home/base_popup.html
{% load i18n static compress %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:'en-us' }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}{% endblock %}</title>
{% compress css %}
<link type="text/x-scss" href="{% static 'theme.scss' %}" rel="stylesheet" media="screen">
{% endcompress %}

<!--<link rel="stylesheet"  href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}">-->
<script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<script src="{% static 'js/jquery/jquery.js' %}"></script>

<!-- extrascript -->
{% block extrascript %}{% endblock %}
<!-- END extrascript -->

<!-- extrastyle -->
{% block extrastyle %}{% endblock %}
<!-- END extrastyle -->

{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static 'admin/css/rtl.css' %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    {% if LANGUAGE_BIDI %}<link rel='stylesheet' type='text/css' href="{% static 'admin/css/responsive_rtl.css' %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
<!--  CSS Custom   -->
<link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">

</head>


<body class="">
<!-- Container -->
<div id="container-sm">
    <div class="content">
    {% block content %}

    {% endblock %}
    </div>
</div>
</body>
</html>

digisafe/home/templates/home/home_base.html
{% extends "home/base.html" %}

{% block title %}Digi.Safe.{% endblock %}

{% block branding %}
<h1 id="site-name" class="float-start"><a href="{% url 'home:index' %}">{{ _('Digi.Safe.') }}</a></h1>
{% endblock %}

{% block nav-bar %}
<!-- As a link -->
<div class="navbar-nav me-auto mb-4 mb-lg-0">
    <a class="nav-link text-white" href="{% url 'home:index' %}">Home</a>

    {% if user.is_anonymous %}
    <a class="nav-link text-white" href="{% url 'account:index' %}">Login</a>

    {% else %}
    <a class="nav-link text-white" href="{% url 'account:index' %}">Account</a>

    {% if user.profile.administrator %}
    <a class="nav-link text-white" href="{% url 'companies:home' %}">Company</a>
    {% endif %}

    {% endif %}

</div>
{% endblock %}

digisafe/home/templates/home/index.html
{% extends "home/home_base.html" %}
{% load i18n static  %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}
{% block nav-bar-sub %}{% endblock %}
{% block content %}

<div class="container">
    <h1 class="text-center m-3"></h1>
    <div class="text-center border-bottom m-4">
        <h1 class="text-center">
            {% translate "Professional, Technician and Business Network Organization" %}
        </h1>
        <p><img src="{% static 'imgs/home/online-learning.png' %}"> {% translate "Manage Training Center" %}</p>
        <p> {% translate "Manage Training Institution" %} <img src="{% static 'imgs/home/macro.png' %}"></p>
        <p><img src="{% static 'imgs/home/company.png' %}"> {% translate "Manage Company" %}</p>
        <p> {% translate "Manage Professionals" %} <img src="{% static 'imgs/home/civil_engineer.png' %}"></p>
        <p><img src="{% static 'imgs/home/operator.png' %}"> {% translate "Manage Technicians" %}</p>
        <p> {% translate "Manage Trainers" %} <img src="{% static 'imgs/home/teacher.png' %}"></p>
        <p><img src="{% static 'imgs/home/network.png' %}"> {% translate "Private Electronic Market" %}</p>
    </div>
    <div class="text-center">
        <img class="img-fluid rounded float-start m-4" src="{% static 'imgs/home/responsive.jpg' %}">
        <h1 class=" fw-bold">{% translate "Total Responsive technology" %}</h1>
    </div>
    <div class="clearfix m-4 border-bottom"></div>
    <div class="text-center fw-bold">
        <img class="img-fluid rounded float-end m-4" src="{% static 'imgs/home/mappa.png' %}">
        <h1 class=" fw-bold">{% translate "Map easy use search" %}</h1>
    </div>
    <div class="clearfix mb-4 border-bottom"></div>
    <div class="text-center mb-4 fw-bold">
        <img class="img-fluid rounded float-start m-4" src="{% static 'imgs/home/timeline.png' %}">
        <h1 class=" fw-bold">{% translate "Timeline free and busy users" %}</h1>
    </div>
    <div class="clearfix mb-4 border-bottom"></div>
    <div class="text-center mb-4 fw-bold">
        <img class="img-fluid  rounded float-end m-4" src="{% static 'imgs/home/agenda.png' %}">
        <h1 class=" fw-bold">{% translate "Synchronized calendar" %}</h1>
    </div>
    <div class="clearfix mb-4 border-bottom"></div>
</div>


{% endblock %}