digisafe/account/urls.py
from django.urls import path, include

from .views import accountView, logoutView, loginView, loginLostView, \
    changePasswordView, resetPasswordView, setPosition, certificateView, \
    dissociateCompanyView, searchCourseView, calendarView, CalendarDelEventView, \
    CalendarFormEventView, CalendarAddView, coursesView, indexView, SettingsView, \
    WorkSessionView


urlpatterns = [
    path('', indexView, name="index"),
    path('courses/', coursesView, name="courses"),
    path('settings/<int:pk>/', SettingsView.as_view(), name="settings"),
    path('agenda/view/', calendarView, name="calendar"),
    path('agenda/set/<int:year>/<int:month>/', calendarView, name="calendar-set"),
    path('agenda/add/<int:year>/<int:month>/<int:day>/', CalendarAddView.as_view(), name="calendar-add"),
    path('agenda/edit/<int:pk>/date/<int:year>/<int:month>/<int:day>/',
         CalendarFormEventView.as_view(), name="calendar-edit"),
    path('agenda/del/<int:pk>/', CalendarDelEventView.as_view(), name="calendar-del"),

    path('company/<int:pk>/dissociate/', dissociateCompanyView, name="dissociate"),
    path('login/', loginView, name="login"),
    path('logout/', logoutView, name="logout"),
    path('loginlost/', loginLostView, name="login-lost"),
    path('changepassword/', changePasswordView, name="change-password"),
    path('resetpassword/', resetPasswordView, name="reset-password"),
    path('user/setposition', setPosition, name="setposition"),
    path('protocol/<int:pk_protocol>/view/', certificateView, name="view-certificate"),
    path('searchcourse/', searchCourseView, name="searchcourse"),

    # work session book
    path('worksessions/', WorkSessionView.as_view(), name="worksessions"),
]

digisafe/digisafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from protocol.views import ProtocolAutocompleteJsonView, protocol_download_file, protocol_download_sign_file
from users.views import CheckExistObjJsonView

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='home')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('accounts/', include(('account.urls', 'accounts'), namespace='accounts')),
    path('company/', include(('companies.urls', 'companies'), namespace='companies')),
    path('institutions/', include(('institutions.urls', 'institutions'), namespace='institutions')),
    path('maps/', include(('maps.urls', 'maps'), namespace='maps')),
    path('jobs/', include(('job.urls', 'job'), namespace='job')),
    path('pricelist/', include(('pricelist.urls', 'job'), namespace='pricelist')),

    path('admin/autocomplete_check_field/', CheckExistObjJsonView.as_view()), #completamento automatico del campo
    path('admin/', admin.site.urls),

    path('tinymce/', include('tinymce.urls')),  # WYSIWYG editor

    path('countries/', include('countries.urls')),
    path('protocol/', include('protocol.urls')),
    path('document/<str:path>/', protocol_download_file, name="protocol-download-file"),
    path('signs/<str:path>/', protocol_download_sign_file, name="protocol-sign-file"),

] + static("/imgs/", document_root=settings.STATIC_ROOT / "imgs")

handler404 = 'home.views.custom_page_not_found_view'
handler500 = 'home.views.custom_error_view'
handler403 = 'home.views.custom_permission_denied_view'
handler400 = 'home.views.custom_bad_request_view'

digisafe/job/urls.py
from django.urls import path, include

from .views import job_user_info, index

urlpatterns = [
    path('<int:pk>/info/', index, name="info"),
    path('userjobinfo/', job_user_info, name="user-job-info"),
]

digisafe/templates/calendar/index.html
{% load i18n static accounttags %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div class="">

{# include 'calendar/modal.html' #}

<DIV class="m-2">

    {# TITOLO #}
    <h1 class="bg-primary bg-opacity-25 text-dark fs-3 p-2"><span class="">{% translate 'Agenda Panel' %}</span></h1>

    <div class="calendar">

        {# BARRA NAVIGAZIONE MESE #}
        <h1 class="calendar-head text-center fs-1">
            <div class="float-start"><a href="{% url 'account:calendar' %}"><i class="bi bi-calendar-event"></i></a></div>
            {% calendar_before_month_name year month as before %}
            {% calendar_next_month_name year month as next %}
            <div class="d-inline "><a href="{% url 'account:calendar-set' before|date:'Y' before|date:'n' %}"><i class="bi bi-arrow-left-square"></i></a></div>
            <div class="d-inline">{% calendar_month_name year month as date %}{{date|date:"F"}}, {{date|date:"Y"}}</div>
            <div class="d-inline "><a href="{% url 'account:calendar-set' next|date:'Y' next|date:'n' %}"><i class="bi bi-arrow-right-square"></i></a></div>
        </h1>

        {# CALENDARIO #}
        <div class="calendar-body">

            {# NOMI SETTIMANA #}
            <div class="row">
            {% calendar_day_name as day_names %}
            {% for day_name in day_names %}
                <div class="card col px-0 text-truncate {% if day_name == 'Saturday' or day_name == 'Sunday' %}text-white bg-primary{% else %}text-dark bg-light{% endif %}   fw-bold text-center border mb-1">
                    {% translate day_name %}
                </div>
            {% endfor %}
            </div>

            {# DISTRIBUZIONE MESE #}
            {% calendar_tmpl year month as weeks %}
            {% for week in weeks %}
            <div class="row">
                {% for day in week %}
                    {% calendar_event user day as events %}
                    <div class="card col text-center border-start border-end p-0 {% if not events %} bg-success {% endif %}" style="min-height: 100px;">
                        <div class="card-header {% if day|date:'w'  == '0' or day|date:'w'  == '6' %}text-white bg-primary{% else %}text-dark bg-light{% endif %}  fw-bold p-0">
                            <div class="float-start ">
                                <a class="{% if day|date:'w'  == '0' or day|date:'w'  == '6' %}text-white bg-primary{% else %}text-dark bg-light{% endif %}" href="{% url 'account:calendar-add' day|date:'Y' day|date:'m' day|date:'j' %}">
                                    <i class="bi bi-calendar-plus"></i>
                                </a>
                            </div>
                            <div>
                            {% calendar_is_today day|date:'Y' day|date:'m' day|date:'d' as is_today %}
                            {% if is_today %}
                                <span class="bg-secondary rounded-pill px-1">{{ day|date:"d, M" }}</span>
                            {% else %}
                                <span>{{ day|date:"d, M" }}</span>
                            {% endif %}
                            </div>
                        </div>
                        <div class="card-body {% if day|date:'w'  == '0' or day|date:'w'  == '6' %}{% else %}{% endif %} p-0">
                            {% for event in events %}
                            <div>
                                {% if event.anonymous %}
                                <p>{% translate 'Busy' %}</p>
                                {% else %}
                                <div id="event_id_{{event.id}}" class="text-truncate ">
                                    <a class="badge bg-secondary" id="calendar_edit_event" data-toggle="modal" href="{% url 'account:calendar-edit' event.id day.year day.month day.day %}" data-target="#modal" title="Edit event" data-tooltip>
                                    {{event.object}}
                                    </a>

                                </div>
                                {% endif %}
                            </div>
                            {% empty %}
                            <div>
                                <p>{% translate 'Free' %}</p>
                            </div>
                            {% endfor %}

                        </div>
                    </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        <div class="calendar-footer"></div>

    </div>
</DIV>

</div>

{% endblock %}

digisafe/templates/calendar/modal.html
<!-- Modal -->
<div id="popup" class="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
</div>

<script>


$(window).on('load', function() {
    $(function () {
        $("input#datatimepicker").datetimepicker({
          //format: 'd/m/Y H:i',
          format: 'Y-m-d H:i',
        });
    });

    $("a#calendar_edit_event").each(function(index) {
        //console.log(index, $(this));
        $(this).on("click", function (e) {
            e.preventDefault();
            //console.log("calendar_edit_event click", e);
            //console.log("calendar_edit_event href", $(this).attr('href'));
            var url = $(this).attr('href');
            var popup = $('#popup');

            $.ajax({
                type: 'GET',
                url: url,
                data: {
                    //csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (response) {
                    //console.log(response);
                    //modal.text( response );
                    html = $.parseHTML( response );
                    popup.html( html );
                    //var my_modal = new bootstrap.Modal(document.getElementById('staticBackdrop'));
                    var my_modal = new bootstrap.Modal(popup);
                    my_modal.show();
                    //disable_modal_form();
                    evalJSFromHtml(response);
                },
                error: function (response) {
                    console.log("Error");
                    //console.log(response["responseJSON"]["error"]);
                    console.log(response);
                }
            });
        });
    });
});

function disable_modal_form(){
    $("#item_update_form input").attr("disabled", "");
    $("#item_update_form textarea").attr("disabled", "");
    $("a#delete_button").addClass("disabled");
}

function toggle_modal_inputs(e){
    var ischecked = e.checked;
    if (ischecked){
        $("#item_update_form input").removeAttr("disabled");
        $("#item_update_form textarea").removeAttr("disabled");
        $("a#delete_button").removeClass("disabled");
    }
    else{
        $("#item_update_form input").attr("disabled", "");
        $("#item_update_form textarea").attr("disabled", "");
        $("a#delete_button").addClass("disabled");
    };
};

function evalJSFromHtml(html) {
    console.log("eval script");
    var newElement = document.createElement('div');
    newElement.innerHTML = html;
    var scripts = newElement.getElementsByTagName("script");
    for (var i = 0; i < scripts.length; ++i) {
        var script = scripts[i]; eval(script.innerHTML);
        };
};
</script>